version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'ci'
      include: 'scope'
    labels:
      - 'github-actions'
      - 'dependencies'
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'deps'
      include: 'scope'
    labels:
      - 'javascript'
      - 'dependencies'
    versioning-strategy: increase
    groups:
      npm-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'bundler'
    directory: '/docs'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'deps'
      include: 'scope'
    labels:
      - 'ruby'
      - 'dependencies'
    groups:
      bundler-dependencies:
        patterns:
          - '*'
